### ISSUE TITLE
HTTPS_PROXY with HTTP Proxy and google HTTPS URLs does not work. 

### ISSUE THREAD

**Issue by refextu** [googleapis/nodejs-storage#277]
#### Environment details

  - OS: all
  - Node.js version: 8
  - npm version: 5.6.0
  - `@google-cloud/storage` version: 1.7.0
(1.6.0 is fine)

#### Steps to reproduce

  1. Setup HTTP Proxy
  2. Start NodeJS with ENV: `HTTPS_PROXY=http://proxy...`
  3. upload file to bucket

#### Information on the root-cause

nodejs-storage uses
* https://github.com/google/google-auth-library-nodejs

which uses gcs-resumable-upload
* https://github.com/stephenplusplus/gcs-resumable-upload

which uses axios and the issue: 
* https://github.com/google/google-auth-library-nodejs/issues/352

issues at axios
* https://github.com/axios/axios/issues/925
* https://github.com/axios/axios/issues/1371

pullrequest (open since 1 year caused by `bad weather`)

* https://github.com/axios/axios/pull/959

**Comment by stephenplusplus** [comment]
It looks like the axios PR was merged. We probably just need a new release, then we'll all be updated automatically?

cc @JustinBeckwith

**Comment by JustinBeckwith** [comment]
Working on it :) 

@refextu - can you share the specific setup of your upstream proxy?  I am struggling to recreate the issue, even though it's obvious there's a problem. Anything you can offer here in the way of a repro would be super helpful.

Also - if I create a patch, would you be willing to try that?

**Comment by refextu** [comment]
@JustinBeckwith You can use Docker ans Squid for local testing:

`docker run --publish 3128:3128 sameersbn/squid:3.3.8-23`

I'm happy to test a patch.

**Comment by stephenplusplus** [comment]
@JustinBeckwith it seems like we have more proxy probs:

- https://github.com/googleapis/nodejs-pubsub/issues/133
- https://github.com/googleapis/nodejs-bigquery/issues/104

Do you think these all chase back to https://github.com/axios/axios/pull/959? There's been some activity on that PR that suggests the fix was not final.

**Comment by JustinBeckwith** [comment]
Possibly, maybe, it depends.  I'll be a lot more confident once we upgrade to v0.24.0 of nodejs-common.

**Comment by stephenplusplus** [comment]
[We've upgraded](https://github.com/googleapis/nodejs-storage/commit/4e6b942c80948cebd9256a596dd61ce9b140b77e)! @JustinBeckwith How's the confidence level? 🎚

**Comment by JustinBeckwith** [comment]
@refextu can you give the 2.x release a shot and let us know if it works?

**Comment by stephenplusplus** [comment]
@JustinBeckwith if this is fixed, would you suspect https://github.com/googleapis/nodejs-pubsub/issues/133 is fixed as well?

**Comment by refextu** [comment]
will check later

**Comment by refextu** [comment]
tested 2.0.3 got error:
`write EPROTO 140735840650112:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827`

**Comment by stephenplusplus** [comment]
Thanks for the update @refextu.

For now, I'll mark this issue as blocked, as 0.19.0 has still not been released.

**Comment by Matt11** [comment]
@stephenplusplus - Is this still blocked? Remember there is another issue related to it (https://github.com/googleapis/nodejs-pubsub/issues/133).

**Comment by stephenplusplus** [comment]
@JustinBeckwith I believe you had been working on the Axios + Proxy issues-- do you know what became of that, and if your prior work would have fixed this?

**Comment by JustinBeckwith** [comment]
This *should* be fixed in the latest version of google-auth-library.  We implemented a work-around that goes around Axios here:
https://github.com/googleapis/google-auth-library-nodejs/blob/master/src/transporters.ts#L102

I am not the best at setting up or testing proxies :) Would it be possible to set up a proxy server or something in long-door-651 for when we need to debug stuff like this?

**Comment by fueltank34** [comment]
If it helps, I ended up getting through the proxy by using this
https://www.npmjs.com/package/global-tunnel-ng

**Comment by stephenplusplus** [comment]
@referx would you mind testing this again? I haven't been able to reproduce in my testing, but I'm not confident I can mirror your environment accurately enough to promise it has been resolved.

**Comment by mainephd** [comment]
This appears to still be an issue as of v35.0.0. @stephenplusplus https://github.com/googleapis/nodejs-pubsub/issues/133#issuecomment-443708636

**Comment by stephenplusplus** [comment]
Hello, all! @google-cloud/storage v2.4.0 was released, which hopefully fixes this issue. Would anyone mind testing?

**Comment by refextu** [comment]
Thanks, I can confirm, that this is working like a breeze. 👍

**Comment by hgardneriv** [comment]
> I'm going to close, but please comment back if things are 👎

Hello, we are seeing this proxy issue with: "@google-cloud/storage": "^5.8.3", still happening when upgrading to: "@google-cloud/storage": "^5.14.1". Discovered while regression testing and upgrade to the Pub/Sub library to address the same problem (proxy not working). In the case of Pub/Sub, the issue was addressed by upgrading to: "@google-cloud/pubsub": "^2.17.0". 

Here's the error as reported by the proxy:

<img width="649" alt="Screen Shot 2021-09-13 at 8 42 54 AM" src="https://user-images.githubusercontent.com/9706538/133100793-c7210cce-c625-40e2-9c42-0129f52aa934.png">

Here are env vars we are using to configure node for use with the proxy:

export NODE_TLS_REJECT_UNAUTHORIZED=0
export HTTP_PROXY="http://localhost:3128"
export http_proxy="http://localhost:3128"
export https_proxy="http://localhost:3128"
export HTTPS_PROXY="http://localhost:3128"
export GRPC_PROXY_EXP="http://localhost:3128"
export grpc_proxy="http://localhost:3128"

The command to start the proxy:

mitmdump --set stream_large_bodies=1 --listen-port 3128

**Comment by JustinBeckwith** [comment]
Greetings @hgardneriv!  Could we trouble you to put this into a new issue?  Sometimes its hard for us to track things in closed / old issues like this :) Thanks!

**Comment by hgardneriv** [comment]
> Greetings @hgardneriv! Could we trouble you to put this into a new issue? Sometimes its hard for us to track things in closed / old issues like this :) Thanks!

Will do!
